### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oceanBigOne** [oceanBigOne/jm#14]
Voir quelle est la bonne License à utiliser sur ce projet. (pour moi la plus permissive possible)

**Comment by oceanBigOne** [comment]
Finalement, je pense laisser le projet en license MIT (qui me semble le plus open possible). La réutilisation à des fins commerciale ne me pose pas de problème.

**Comment by Edem13** [comment]
Objectif = que la licence ne soit pas un obstacle à l'utilisation du code par d'autres développeurs ?
Hypothèse de réflexion (tu me diras si elle est plausible) : ta version est forkée et la version forkée est soumise à une licence très restrictive (et l'auteur ne souhaite pas partager son code) alors qu'il y a des améliorations intéressantes. Qu'est-ce qui est préférable : que ta version reste inchangée jusqu'à ce qu'un libriste imagine les mêmes améliorations ? ou que les améliorations non-libres existent (et soient connues) en espérant qu'un libriste (toi au pire) développera un autre code libre pour faire la même chose ?

**Comment by oceanBigOne** [comment]
Je dirai 2) : "que les améliorations non-libres existent (et soient connues) en espérant qu'un libriste (toi au pire) développera un autre code libre pour faire la même chose ?"... pour pas bloquer...

**Comment by Edem13** [comment]
Alors MIT c'est (effectivement) ce qu'il faut :-) !
