### ISSUE TITLE
Valeur par défaut et condition de saisie

### ISSUE THREAD

**Issue by RomainLalande** [oceanBigOne/jm#18]
Bonjour,
Lorsque l'on arrive sur la page de vote, le vote par défaut est "à rejeter". En temre d'usage il serait plus intuitif de : 

- tout déselectionner par défaut lorsque l'on arrive sur la page
- avoir une condition de saisie "s'être prononcé sur chaque proposition" pour voter
- ajouter une case visuellement séparée "pas de préférence à exprimer / pas d'avis sur la question"

Cela éviterait certaines saisies involontaires :-) 

Merci en tous cas pour ce service qui saura être bien utile ! 

Mes 2 cts, 

Romain

**Comment by oceanBigOne** [comment]
C'est noté, merci ! (je vais effectivement retirer la saisie par défaut) En revanche, je ne suis pas d'accord avec le "pas d'avis". Avec le jugement majoritaire on part justement du principe qu'une absence d'avis signifie "a rejeter".. car c'est la mention la plus "négative" et pas une sorte de mention "neutre". 

Je crois que l'idée derrière est de dire que personne ne veut voir gagner une proposition sur laquelle "on a pas d'avis"... Lors d'une élection on risquerai d'élire le candidat ayant recueilli le plus de 'pas d'avis'...ce qui serait un non sens (pas sûr de bien m'exprimer...)

**Comment by RomainLalande** [comment]
Assez d'accord finalement, je ne suis pas très au fait du mode de scrutin :-)
