### ISSUE TITLE
Fermer le vote une fois que tous les participants ont voté

### ISSUE THREAD

**Issue by petersg83** [oceanBigOne/jm#20]
Bonjour,

Tout d'abord un grand merci pour ce travail, ça fait un moment que je cherche une site/logiciel où chacun peut voter l'un après l'autre sur un ordinateur et ton projet est le seul que j'ai trouvé faisant ça !

Dans mon cas c'est dans une école démocratique que l'on veut mettre en place le jugement majoritaire pour les élections avec candidats et il serait pratique de pouvoir avoir accès aux résultats une fois que tout le monde a voté, sans attendre que le temps soit écoulé.
Peut-être avec un lien spécial qui permettrait d'administrer le vote en question ?
Ou en mettant en avance le nombre de votants total ?

Merci beaucoup !

**Comment by petersg83** [comment]
Ah super ! Je viens de tester et ça fonctionne bien :)
C'est super utile. Je suis d'accord avec toi et je ne communiquerai pas cette petite astuce pour que les votes ne soient pas biaisés.
En attendant la version finale ça fera très bien l'affaire !

Bonne idée pour les options avancées !

Merci beaucoup :)

**Comment by oceanBigOne** [comment]
@petersg83 . C'est bon, je viens de mettre en ligne les options dont nous avons discuté ici (limitation du nombre de votant et accès aux résultats encours de vote). J'ai donc retiré la variable ?show-result qui n'a plus d'utilité.
