### ISSUE TITLE
Politique de confidentialité : manque données chez google

### ISSUE THREAD

**Issue by Cyrille37** [oceanBigOne/jm#22]
Bonjour,
La "Politique de confidentialité" est un peu fausse, il n'est pas fait mention qu'en visitant ce site ont utilise des sites de Google fonts.googleapi.com et fonts.gstatic.com, qui sait, en autre chose, que nous avons visité jugementmajoritaire.net.
![image](https://user-images.githubusercontent.com/368965/52859937-61c3f680-312e-11e9-9e6d-ed827a4b8c7f.png)

**Comment by Cyrille37** [comment]
En fait quand on visite le site jugementmajoritaire.net on le signale à beaucoup d'autres sites tiers : 
![image](https://user-images.githubusercontent.com/368965/52860140-e747a680-312e-11e9-988f-befd3b76784d.png)

**Comment by oceanBigOne** [comment]
Bonjour,

Merci pour votre vigilance. Youtube n'est présent que sur la page d'accueil à cause de la vidéo, mais vous avez clairement raison. Je vais faire le nécessaire dès que possible pour supprimer ces liens avec Google (héberger la vidéo et les fonts sur le site en lui même).

**Comment by Cyrille37** [comment]
Ça ne me dérange pas en soi que vous utilisiez des sites tiers, chacun est libre.
Par contre la "Politique de confidentialité" laisse entendre qu'aucune donnée n'est captée, alors que ce n'est pas le cas ... ;-)

**Comment by oceanBigOne** [comment]
La politique de confidentialité reflète réellement ce que j'ai voulu faire. C'est clairement une erreur de ma part.
