### ISSUE TITLE
Ajout un moyen de modifier les propositions

### ISSUE THREAD

**Issue by oceanBigOne** [oceanBigOne/jm#4]
Si on peut pas modifier --> page de visualisation avant validation OU lien 'admin' comme sur framadate OU message 'attention une fois validé plus possible de modifier'

**Comment by oceanBigOne** [comment]
@Edem13 , ok pour la page de visualisation et le message d'alerte. Mais pour moi, la modif est une mauvaise idée (car cela peut engendrer de la méfiance dans le résultat).

**Comment by oceanBigOne** [comment]
La message d'alerte suffit-il ? (j'ai l'impression que oui)

**Comment by Edem13** [comment]
Dans une optique pédagogique je suis ok que le message d'alerte suffit tel quel (même si spontanément je me sentirais plus rassuré par un système de "double clic". On ne peut pas empêcher les gens trop pressés de cliquer avant de réfléchir, même en multipliant les "alertes" et c'est pas plus mal si certains valident trop vite, ça leur permettra d'y réfléchir à deux fois la fois suivante :-)
