### ISSUE TITLE
Evolutions histogrammes

### ISSUE THREAD

**Issue by oceanBigOne** [oceanBigOne/jm#9]
- mettre les taux en abscisse en haut et les propositions (titres) en ordonnee à gauche (pour qu'on puisse bien les lire)
- faire un trait à 50% pour mieux visualiser.
- intégrer les pourcentages

**Comment by oceanBigOne** [comment]
J'ai fais les modifs, sauf l'intégration des pourcentages (pas prévu par la lib que j'utilise et cela me semble poser des problèmes d'affichages en fonction des différentes résolutions (si la tranche est trop petite pour afficher le pourcentage)

**Comment by Edem13** [comment]
C'est moi où la ''hauteur'' de l'histogramme est toujours la même et du coup quand il y a peu de propositions (3 dans mon test) les bandes de couleur de l'histogramme sont assez éloignées les unes des autres ? Avec 10 propositions  l'espace entre les bandes de couleur est plutôt bon (NB : selon la longueur du libellé des propositions ça peut déborder sur les bandes au-dessus et en-dessous).

**Comment by oceanBigOne** [comment]
Trés bonne remarque, je crois que c'est bien le cas puisqu'à l'origine il était horizontal... Je vais vérifié et corriger ca.
